name: New WF
on:
  workflow_dispatch:
    inputs:
      your_name:
        description: Enter your name
        required: true
        type: string

env:
  person_name: ${{ inputs.your_name }}

jobs:
  test_job:
    runs-on: ubuntu-latest
    outputs:
      person: ${{ steps.disp.outputs.individual }}
    steps:
      - name: Greeting to Person
        id: disp
        run: echo "individual=$person_name" >> $GITHUB_OUTPUT

  test_job2:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "${{ needs.test_job.outputs.person }}"
