name: New WF
on:
  workflow_dispatch:
    inputs:
      your_name:
        description: Enter your name
        required: true
        type: string

env:
  person_name: ${{ inputs.your_name }}

jobs:
  test_job:
    runs-on: ubuntu-latest
    outputs:
      person: ${{ steps.disp.outputs.individual }}
      addr: ${{ steps.disp.outputs.address }}        
      phn: ${{ steps.disp.outputs.phone }}
    env:
      add: 'test add'
    steps:
      - name: Greeting to Person
        id: disp
        env:
          phone: 12345678
        run: |
          {
            echo "individual=$person_name"
            echo "address=$add"
            echo "phone=$phone"
          } >> $GITHUB_OUTPUT

  test_job2:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "${{ needs.test_job.outputs.person }}, ${{ needs.test_job.outputs.addr }}, ${{ needs.test_job.outputs.phn }}"
      - name: Get Repo Var
        run: "echo $TEST_VAR" >> testfile.txt
      - name: upload test var
        uses: actions/upload-artifact@v7
        with:
          name: test-var
          path: testfile.txt
